Add flight booking AI Agent demo #817 (#818)
* Add flight booking AI Agent demo

* Modify the description error in the prompt word

* Added Readme file for ticket booking operation instructions

* Delete useless comments

* Add interface and service to bookflight

1. Modify and add callback function to handle streaming output and other returns of returned content
2. Modify the implementation of the Invoke function and call the Chat function in Ollama to implement it

* fix: go.mod, go.sum

* fix CI/ubuntu-latest-Go 1.23; golangci-lint / lint(1.23)

* fix CI/ubuntu-latest-Go 1.23; golangci-lint / lint(1.23)

* fix:llm/book-flight/go-server/main.go:59:20: not enough arguments in call to cot.Run

* Delete llm/book-flight/go-server/main.go

* Add environment variable files and perform unified verification to avoid repeated loading.

* Fixed the problem that the Ollama model configuration parameter loading logic error caused the function callback to fail correctly.

* Modify the prompt word loading method and divide the functions.

* Add proto in llm/book-flight and no longer depend on llm/proto.

* Modify frontend

* Modify the front-end file so that the content and record contents are displayed in different dialog boxes respectively.

* Modify the agent callback function to stream the agent's thinking process to the recording box.

* Fix yaml version issue

* Modify the sample document for booking a flight

* The intelligent agent adds the ability to have multi-round conversations.

* Fix CI-lint

* add: chatbot and record gap

* add: fight book successful message

* Remove the .env file, which is a private file for the user and should not be submitted to the code base.

* Add *.env to .gitignore to prevent developers from accidentally committing the file.

* Fixed the issue that current_content is nil caused the system to not run normally.

* Added 8 task states, six of which are derived from the definition of task states in A2A.

* Formatting import packages

* Optimize prompt words

Combine TaskState proposed by A2A, and differentiate prompt word templates.

* Modify the Action

Modify the Action parameters to comply with JSON-RPC2.0 to prepare for docking with MCP.

* Add toolkit management to manage a set of tools.

Provides the QueryTool interface to find tools in a toolkit, the Description interface to return an overview of the toolkit, and the ToolsDescription interface to return descriptions of all tools in the toolkit.

* Adjust the agent process for the addition of new modules

* Fix: ineffectual assignment to rst (ineffassign)

* fixed: {content} not being correctly replaced in summary prompts.

* Add CreateTaskToolkit parameters

Pass the Toolkit documentation through parameters.

* Add CreateTool method to create tools uniformly.

* Fixed: Dependent packages are not imported in groups

* Fixed: Memory error causing missions to not complete properly.

* Fixed:  use panic

* Fixed: use strings.builder or other ways to reuse malloc memory

* Fixed: history will keep growing, would it be better to limit the length

* Fixed: maxContextCount is a default value, make it to const

* Fixed: It appears there is a typo in the comment ('shot' should be 'short'). Consider updating the comment to 'A String providing a short description of the error.'

* Fixed: The 'TaskUnrelatedTool' is appended unconditionally and then is potentially appended again if the 'TaskUnrelated' flag is set later. This could lead to duplicate tool entries. Consider removing the unconditional append or reviewing the flag logic.

* Fixed: The HTML tag 'span1' is non-standard. It is recommended to change it to a standard tag such as 'span' for better browser compatibility.

* Fixed: Use string.builder to reuse malloc memory

* Fix: All "Id" in the code were changed to ID

* Fix: In Chinese documents, add a half-width space between English and Arabic words and the Chinese characters before and after them.

* Fix: If multiple var, const or type appear in succession, use var(), const() or type(), and then put all the contents in this bracket.

* Fix: refactor(configuration): Refactor environment variable configuration to enhance maintainability

Centralize the loading logic of environment variables into `config.go`, and add `AtoiWithDefault` function to handle default values. At the same time, update the `.env.example` file to include new client and web settings, and use unified configuration variables in multiple files to reduce hard coding.

---------

Co-authored-by: 邓爱琪 <magic_8@qq.com>